#!/usr/bin/env bash
# Openclaw whitelist configuration

build_openclaw_whitelist() {
    local service_user="${MINIPC_SERVICE_USER}"

    cat > "/etc/sudoers.d/${service_user}" << EOF
# Allow openclaw to run specific commands without password
# Generated by headless-setup

# APT operations for package management
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/apt *

# Systemd service management
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl *
${service_user} ALL=(ALL) NOPASSWD: /bin/systemctl *

# File and directory management
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/mkdir *
${service_user} ALL=(ALL) NOPASSWD: /bin/mkdir *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/rm *
${service_user} ALL=(ALL) NOPASSWD: /bin/rm *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/mv *
${service_user} ALL=(ALL) NOPASSWD: /bin/mv *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/cp *
${service_user} ALL=(ALL) NOPASSWD: /bin/cp *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/tee *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/touch *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/cat *
${service_user} ALL=(ALL) NOPASSWD: /bin/cat *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/ls *
${service_user} ALL=(ALL) NOPASSWD: /bin/ls *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/find *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/grep *
${service_user} ALL=(ALL) NOPASSWD: /bin/grep *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/head *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/tail *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/sed *
${service_user} ALL=(ALL) NOPASSWD: /bin/sed *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/awk *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/cut *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/sort *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/uniq *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/wc *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/tr *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/xargs *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/which *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/whereis *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/file *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/stat *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/chmod *
${service_user} ALL=(ALL) NOPASSWD: /bin/chmod *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/chown *
${service_user} ALL=(ALL) NOPASSWD: /bin/chown *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/ln *
${service_user} ALL=(ALL) NOPASSWD: /bin/ln *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/readlink *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/dirname *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/basename *

# Git operations
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/git *

# Python and pip
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/python3 *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/pip3 *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/pip *
${service_user} ALL=(ALL) NOPASSWD: /usr/local/bin/pip3 *
${service_user} ALL=(ALL) NOPASSWD: /usr/local/bin/pip *

# Node.js and npm
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/node *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/npm *
${service_user} ALL=(ALL) NOPASSWD: /usr/local/bin/node *
${service_user} ALL=(ALL) NOPASSWD: /usr/local/bin/npm *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/npx *
${service_user} ALL=(ALL) NOPASSWD: /usr/local/bin/npx *

# Docker
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/docker *
${service_user} ALL=(ALL) NOPASSWD: /usr/local/bin/docker *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/docker-compose *
${service_user} ALL=(ALL) NOPASSWD: /usr/local/bin/docker-compose *

# Network tools
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/curl *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/wget *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/ping *
${service_user} ALL=(ALL) NOPASSWD: /bin/ping *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/netstat *
${service_user} ALL=(ALL) NOPASSWD: /bin/netstat *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/ss *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/dig *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/nslookup *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/host *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/whois *

# Process management
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/kill *
${service_user} ALL=(ALL) NOPASSWD: /bin/kill *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/pkill *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/killall *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/ps *
${service_user} ALL=(ALL) NOPASSWD: /bin/ps *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/top *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/htop *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/pgrep *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/pidof *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/nohup *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/screen *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/tmux *

# Text editors
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/nano *
${service_user} ALL=(ALL) NOPASSWD: /bin/nano *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/vim *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/vi *
${service_user} ALL=(ALL) NOPASSWD: /bin/vi *

# Archive tools
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/tar *
${service_user} ALL=(ALL) NOPASSWD: /bin/tar *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/gzip *
${service_user} ALL=(ALL) NOPASSWD: /bin/gzip *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/gunzip *
${service_user} ALL=(ALL) NOPASSWD: /bin/gunzip *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/unzip *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/zip *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/bzip2 *
${service_user} ALL=(ALL) NOPASSWD: /bin/bzip2 *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/bunzip2 *
${service_user} ALL=(ALL) NOPASSWD: /bin/bunzip2 *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/xz *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/unxz *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/7z *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/7za *

# System information
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/df *
${service_user} ALL=(ALL) NOPASSWD: /bin/df *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/du *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/free *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/uptime *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/uname *
${service_user} ALL=(ALL) NOPASSWD: /bin/uname *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/hostname *
${service_user} ALL=(ALL) NOPASSWD: /bin/hostname *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/date *
${service_user} ALL=(ALL) NOPASSWD: /bin/date *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/cal *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/bc *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/dc *

# Environment and shell
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/env *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/printenv *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/export *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/echo *
${service_user} ALL=(ALL) NOPASSWD: /bin/echo *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/printf *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/test *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/[ *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/true *
${service_user} ALL=(ALL) NOPASSWD: /bin/true *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/false *
${service_user} ALL=(ALL) NOPASSWD: /bin/false *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/yes *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/seq *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/sleep *
${service_user} ALL=(ALL) NOPASSWD: /bin/sleep *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/timeout *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/time *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/tty *
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/stty *

# Read vault files
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/cat /var/lib/openclaw/vault/*
EOF

    chmod 440 "/etc/sudoers.d/${service_user}"
    visudo -c -f "/etc/sudoers.d/${service_user}"
}
