#!/usr/bin/env bash
# Openclaw whitelist configuration

build_openclaw_whitelist() {
    local service_user="${MINIPC_SERVICE_USER}"

    cat > "/etc/sudoers.d/${service_user}" << EOF
# Allow openclaw to run specific commands without password
# Generated by headless-setup

# APT operations for package management
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/apt update
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/apt upgrade
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/apt install

# Systemd service management (only for configured apps)
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl start openclaw
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop openclaw
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart openclaw
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl status openclaw
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl start anki
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop anki
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart anki
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl status anki
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl start obsidian
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop obsidian
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart obsidian
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl status obsidian
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl start all
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop all
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart all

# Read vault files
${service_user} ALL=(ALL) NOPASSWD: /usr/bin/cat /var/lib/openclaw/vault/*
EOF

    chmod 440 "/etc/sudoers.d/${service_user}"
    visudo -c -f "/etc/sudoers.d/${service_user}"
}
