#!/usr/bin/env bash
# Openclaw whitelist configuration

build_openclaw_whitelist() {
    local service_user="${MINIPC_SERVICE_USER}"

    cat > "/etc/sudoers.d/${service_user}" << 'EOF'
# Allow openclaw to run specific commands without password
# Generated by headless-setup

# APT operations for package management
ALL ALL=(ALL) NOPASSWD: /usr/bin/apt update
ALL ALL=(ALL) NOPASSWD: /usr/bin/apt upgrade
ALL ALL=(ALL) NOPASSWD: /usr/bin/apt install

# Systemd service management
ALL ALL=(ALL) NOPASSWD: /usr/bin/systemctl start
ALL ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop
ALL ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart
ALL ALL=(ALL) NOPASSWD: /usr/bin/systemctl status

# Read vault files
ALL ALL=(ALL) NOPASSWD: /usr/bin/cat /var/lib/openclaw/vault/*
EOF

    chmod 440 "/etc/sudoers.d/${service_user}"
    visudo -c -f "/etc/sudoers.d/${service_user}" &>/dev/null || true
}
